# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SZSocketManager' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SZSocketManager
  pod 'SocketRocket'
  target 'SZSocketManagerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SZSocketManagerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
