# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'SocketRocket_LN' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SocketRocket_LN
  
  target 'SocketRocket_LNTests' do
    inherit! :search_paths
      # Pods for testing
  pod 'SocketRocket'
  end

  target 'SocketRocket_LNUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
